#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────
#  Discord Server Architect — One-Shot Installer
# ─────────────────────────────────────────────────────

# Colors
RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
MAGENTA="\033[35m"

info()    { echo -e "${CYAN}  ℹ  $*${RESET}"; }
success() { echo -e "${GREEN}  ✔  $*${RESET}"; }
warn()    { echo -e "${YELLOW}  ⚠  $*${RESET}"; }
error()   { echo -e "${RED}  ✖  $*${RESET}" >&2; exit 1; }
step()    { echo -e "\n${BOLD}${MAGENTA}▶ $*${RESET}"; }

clear

echo -e "${BOLD}${MAGENTA}"
echo "  ╔═══════════════════════════════════════════════════╗"
echo "  ║     🏰  DISCORD SERVER ARCHITECT INSTALLER  🏰    ║"
echo "  ║          AI-Powered Guild Management — CLI         ║"
echo "  ╚═══════════════════════════════════════════════════╝"
echo -e "${RESET}"

# ─────────────────────────────────────────────────────
# 1. Dependency Checks
# ─────────────────────────────────────────────────────
step "Checking system dependencies..."

if ! command -v node &>/dev/null; then
  error "Node.js is not installed. Install it from https://nodejs.org (v18+ required)."
fi

NODE_VERSION=$(node --version | sed 's/v//')
NODE_MAJOR=$(echo "$NODE_VERSION" | cut -d. -f1)
if [ "$NODE_MAJOR" -lt 18 ]; then
  error "Node.js v18+ required. You have v${NODE_VERSION}. Please upgrade."
fi
success "Node.js v${NODE_VERSION} found."

if ! command -v git &>/dev/null; then
  error "git is not installed. Please install git first."
fi
success "git $(git --version | awk '{print $3}') found."

if ! command -v npm &>/dev/null; then
  error "npm is not installed. It usually ships with Node.js."
fi
success "npm $(npm --version) found."

# ─────────────────────────────────────────────────────
# 2. Clone or use existing repo
# ─────────────────────────────────────────────────────
step "Setting up project files..."

REPO_URL="https://github.com/DXN1-termux/AGENTIC-DC-builder.git"
INSTALL_DIR="discord-server-architect"

if [ -f "package.json" ] && grep -q "discord-server-architect" "package.json" 2>/dev/null; then
  info "Already inside the project directory. Skipping clone."
elif [ -d "$INSTALL_DIR" ]; then
  info "Directory '$INSTALL_DIR' already exists. Pulling latest changes..."
  git -C "$INSTALL_DIR" pull --quiet
  cd "$INSTALL_DIR"
else
  info "Cloning repository..."
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

success "Project files ready."

# ─────────────────────────────────────────────────────
# 3. Install npm dependencies
# ─────────────────────────────────────────────────────
step "Installing npm dependencies..."
npm install --silent
success "Dependencies installed."

# ─────────────────────────────────────────────────────
# 4. Configure credentials
# ─────────────────────────────────────────────────────
step "Configuring credentials..."

ENV_FILE=".env.local"

if [ -f "$ENV_FILE" ]; then
  warn ".env.local already exists. Skipping credential setup."
  warn "Edit '${ENV_FILE}' manually to update keys."
else
  echo -e "\n${DIM}  Press Enter to skip any field (you can set it in .env.local later).${RESET}\n"

  read -rp "  🔑 Google Gemini API Key (from https://aistudio.google.com): " GEMINI_KEY
  read -rp "  🤖 Discord Bot Token:                                         " DISCORD_TOKEN
  read -rp "  🏰 Discord Guild (Server) ID:                                 " GUILD_ID

  {
    echo "# Discord Server Architect — Environment Config"
    echo "# Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M UTC')"
    echo ""
    if [ -n "$GEMINI_KEY" ]; then
      echo "GEMINI_API_KEY=\"${GEMINI_KEY}\""
    else
      echo "# GEMINI_API_KEY=\"your-gemini-api-key\""
    fi
    if [ -n "$DISCORD_TOKEN" ]; then
      echo "DISCORD_TOKEN=\"${DISCORD_TOKEN}\""
    else
      echo "# DISCORD_TOKEN=\"your-discord-bot-token\""
    fi
    if [ -n "$GUILD_ID" ]; then
      echo "GUILD_ID=\"${GUILD_ID}\""
    else
      echo "# GUILD_ID=\"your-guild-id\""
    fi
    echo ""
    echo "APP_URL=\"http://localhost:3000\""
  } > "$ENV_FILE"

  success ".env.local created."
fi

# ─────────────────────────────────────────────────────
# 5. Done — print summary
# ─────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}"
echo "  ╔═══════════════════════════════════════════════════╗"
echo "  ║           ✔  Installation Complete!               ║"
echo "  ╚═══════════════════════════════════════════════════╝"
echo -e "${RESET}"
echo -e "  ${BOLD}To launch the CLI:${RESET}     ${CYAN}npm run cli${RESET}"
echo -e "  ${BOLD}To launch Web GUI:${RESET}     ${CYAN}npm run dev${RESET}"
echo -e "  ${BOLD}For help:${RESET}              ${CYAN}npm run cli -- --help${RESET}"
echo ""

read -rp "  ❓ Launch CLI now? (y/N): " LAUNCH_NOW
if [[ "$LAUNCH_NOW" =~ ^[Yy]$ ]]; then
  echo ""
  npm run cli
fi
